name: organicnom
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: 3.21.2
  font_awesome_flutter: ^8.4.0
  google_fonts: ^1.1.0
  youtube_player_flutter: ^7.0.0+7
  cupertino_icons: ^1.0.0
  
  flutter_vlc_player: ^4.0.2
  cached_network_image:
  flutter_image: ^3.0.0
  

  flutter:
    sdk: flutter
  auth_service:
    path: services/auth_service
  payment_service:
    path: services/payment_service
  data_service:
    path: services/data_service
  db_driver:
    path: services/db_driver
  rupa_box:
    path: services/rupa_box


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  