name: data_service
description: Package that manages the backend data domain
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
      
dev_dependencies:
  flutter_test:
    sdk: flutter