name: data_service
description: Package that manages the backend data domain
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  hive: ^1.4.4+1
  hive_flutter:
  path_provider:
  connectivity: ^2.0.2
  meta: ^1.1.8

  
  db_driver:
    path: ../db_driver

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.9