name: auth_service
description: Package that manages the authentication domain
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.4
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter