name: payment_service
description: Package that manages the payment domain
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  payhere_mobilesdk_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter